In [14]:
import tensorflow as tf

In [15]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model
import pickle

In [16]:
model = load_model('model.h5')

with open('lable_encoder_gender.pkl','rb') as file:
    label_encoder_gender = pickle.load(file)

with open('onehot_encoder.pkl','rb') as file:
    onehot_encoder = pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)

In [17]:
input_data = {
    "credit_score": 650,
    "country": "France",
    "gender": "Male",
    "age": 40,
    "tenure": 5,
    "balance": 60000.0,
    "products_number": 2,
    "credit_card": 1,
    "active_member": 1,
    "estimated_salary": 50000.0
}

In [13]:
country_encoded = onehot_encoder.transform([[input_data['country']]]).toarray()
country_encoded_df = pd.DataFrame(country_encoded, columns=onehot_encoder.get_feature_names_out(['country']))

c:\ANN PROJECT\.venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [19]:
input_df = pd.DataFrame([input_data])
input_df

,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary
0,650,France,Male,40,5,60000.0,2,1,1,50000.0

In [21]:
input_df['gender'] = label_encoder_gender.transform(input_df['gender'])

In [ ]:
input_df = pd.concat([input_df.drop(['country'],axis=1),country_encoded_df],axis=1)

In [26]:
input_df

,credit_score,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,country_France,country_Germany,country_Spain
0,650,1,40,5,60000.0,2,1,1,50000.0,1.0,0.0,0.0

In [27]:
input_scaled=scaler.transform(input_df)

In [28]:
prediction=model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 252ms/step

array([[0.04791178]], dtype=float32)

In [29]:
if prediction[0][0] > 0.5:
    print("Customer is likely to churn")
else:
    print("Customer is not likely to churn")

Customer is not likely to churn